<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <JellyfinVersion>10.11.1</JellyfinVersion>
        <JellyfinNugetVersion Condition="!$(JellyfinVersion.StartsWith('10.11'))">$(JellyfinVersion)</JellyfinNugetVersion>
        <JellyfinNugetVersion Condition="$(JellyfinVersion.StartsWith('10.11'))">10.11.*-*</JellyfinNugetVersion>
        <JellyfinNugetVersion Condition="$(JellyfinVersion.StartsWith('10.11.0'))">10.11.0</JellyfinNugetVersion>
        <TargetFramework Condition="$(JellyfinVersion.StartsWith('10.11'))">net9.0</TargetFramework>
        <TargetFramework Condition="'$(JellyfinVersion)' == '10.10.7'">net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AssemblyName>Jellyfin.Plugin.CollectionSections</AssemblyName>
        <Version>2.3.0.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Jellyfin.Model" Version="$(JellyfinNugetVersion)" />
        <PackageReference Include="Jellyfin.Controller" Version="$(JellyfinNugetVersion)" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Configuration\config.html" />
      <EmbeddedResource Include="Configuration\config.html" />
      <None Include="..\logo.png" CopyToOutputDirectory="Always" />
    </ItemGroup>

    <!-- 10.10.7 Specific Code from non 10.10.7 builds -->
    <ItemGroup Condition="'$(JellyfinVersion)' != '10.10.7'">
        <None Include="JellyfinVersionSpecific/10.10.7/*.cs" />
        <Compile Remove="JellyfinVersionSpecific/10.10.7/*.cs" />
    </ItemGroup>

    <!-- Remove 10.11.0 Specific Code from non 10.11.0 builds -->
    <ItemGroup Condition="'$(JellyfinVersion)' != '10.11.0'">
        <None Include="JellyfinVersionSpecific/10.11.0/*.cs" />
        <Compile Remove="JellyfinVersionSpecific/10.11.0/*.cs" />
    </ItemGroup>
    <ItemGroup Condition="!$(JellyfinVersion.StartsWith('10.11'))">
        <None Include="JellyfinVersionSpecific/10.11/*.cs" />
        <Compile Remove="JellyfinVersionSpecific/10.11/*.cs" />
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="Exists('C:\ProgramData\Jellyfin\Server\plugins\CollectionSections')">
        <Exec Condition="'$(JellyfinVersion)' == '10.11.1'" Command="xcopy $(TargetDir) &quot;C:\ProgramData\Jellyfin\Server\plugins\CollectionSections&quot; /y" />
        <Exec Condition="'$(JellyfinVersion)' == '10.10.7'"     Command="xcopy $(TargetDir) &quot;C:\ProgramData\Jellyfin\Server_10_10_7\plugins\CollectionSections&quot; /y" />
    </Target>
</Project>
